import Head from "next/head";
import styles from "../styles/Home.module.css";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <h1>Stock<span className={styles.green}>alert</span></h1>
        <nav>
          <ul>
            <li>View stocks</li>
            <li>
              {" "}
              <button>Sign in</button>
            </li>
            <li>
              {" "}
              <button>Login</button>
            </li>
          </ul>
        </nav>
      </header>
      <main className={`${styles.main}`}></main>
    </>
  );
}
